### ISSUE TITLE
Inability to use `let` / `struct`

### ISSUE THREAD

**Issue by zdavison** [Hearst-DD/ObjectMapper#156]
Currently, because of the way ObjectMappers `<-` operator functions, there is no way to use `let` properties, and the `Mapper` class itself requires `AnyObject`, so where we'd often like to have immutable structs, we have mutable class instances.

Would be real nice if we could fix this limitation.

**Comment by cezheng** [comment]
If you just don't want the properties to be public mutable, I guess you can make it private(set) like this
```
public private(set) var propertyName: TypeName
```

**Comment by tristanhimmelman** [comment]
ObjectMapper does in fact support `let` type variables, however it requires some extra code to accomplish. There is an example which you can check out in ObjectMapperTests.swift:
https://github.com/Hearst-DD/ObjectMapper/blob/master/ObjectMapperTests/ObjectMapperTests.swift#L685

Otherwise there are other libraries that tackle this requirement more directly for example:
[Himotoki](https://github.com/ikesyo/Himotoki)
