### ISSUE TITLE
Rationale behind the latest newInstance change

### ISSUE THREAD

**Issue by mkoppanen** [Hearst-DD/ObjectMapper#163]
Hello,

I was wondering why the change from using init? was changed to newInstance? The previous method allowed to do validation in init? and return nil if the object did not contain the necessary fields. With a quick glance the current method makes this a bit more awkward.

**Comment by allaire** [comment]
Wondering too :)

**Comment by mladen107** [comment]
Check this issue https://github.com/Hearst-DD/ObjectMapper/issues/141

**Comment by tristanhimmelman** [comment]
I removed the init? method due to popular demand to make the library more compatible with Realm. @mkoppanen I see your point about validation, @mladen107 actually brought up a similar point in the other thread #141 .

If it is a feature that many people want, I am not opposed to updating the protocol.

Perhaps something like:
```
public protocol Mappable {
    static func newInstance(map: Map) -> Mappable?
    mutating func mapping(map: Map)
}

class User: Mappable {
    var username: String?

    class func newInstance(map: Map) -> Mappable? {
        return User()
    }

    func mapping(map: Map) {
        username    <- map["username"]
    }
}
```

Would this be adequate for validation purposes?

**Comment by danhodos** [comment]
This is neat! Could you give an example of how the validation would work in this scenario?

**Comment by tristanhimmelman** [comment]
I just created a branch with my proposed change above. Let me know what you guys think:
https://github.com/Hearst-DD/ObjectMapper/tree/protocol-update

**Comment by danhodos** [comment]
Just read through the code; makes sense to me! :+1: :fireworks: :smile_cat:

**Comment by bennichols** [comment]
This change breaks the library for my use case, I believe. I use a BaseObject: Mappable class with an "id" field that has its own custom transform. I then derive all my object from that BaseObject. The newInstance method is static, which in Swift also means it's final, so I can no longer subclass my Mappable BaseObject.

**Comment by mladen107** [comment]
@bennichols 
Use class method instead of static and it will work! Class methods match static methods in protocols too.

**Comment by tristanhimmelman** [comment]
@mladen107 is correct. See https://github.com/Hearst-DD/ObjectMapper#subclasses

**Comment by mkoppanen** [comment]
https://github.com/Hearst-DD/ObjectMapper/tree/protocol-update makes sense to me

**Comment by andrebraga** [comment]
Also, given an arbitrary persistent store, I believe this is the only way to enforce uniqueness without resorting to really weird tricks. So that's +1 for me and I'm already tracking the protocol-update branch.

May I suggest a relaxation of the signature in order to remain (mostly) source compatible (returning an optional is probably still necessary for some use cases, I believe)? Make the `map` argument optional and defaulted to nil.

`static func newInstance(map: Map? = nil) -> Mappable?`

**Comment by tristanhimmelman** [comment]
@andrebraga thanks for the feedback. 

I like the idea but default values do not seem to be supported within protocols in the current version of Swift.

**Comment by andrebraga** [comment]
True :)

**Comment by tristanhimmelman** [comment]
The protocol-update branch has been merged into master.

Based on #168, however, I am considering reverting to the old protocol as it seems it was already possible to support realm before my change to the protocol.

**Comment by andrebraga** [comment]
My scenario involves Core Data. Unless I'm missing something or Realm already handles this somehow, without access to some unique key on the map I don't see a way to retrieve an existing entity from the persistent store when calling newInstance. I'm open for suggestions.

**Comment by waltermvp** [comment]
@andrebraga same here, not sure if objectmapper handles the  "unique" part of parsing
