### ISSUE TITLE
Generic Mapper for multiple Models

### ISSUE THREAD

**Issue by MoralAlberto** [Hearst-DD/ObjectMapper#197]
Hello,

I want to reuse code in my app, and I have created the next snippet to show how I parse data (in my Question Model).

```swift
static func parse(data: NSData) -> Question {
    var parseError: NSError?
    let parsedObject: AnyObject? = NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions.AllowFragments, error:&parseError)
    let result = Mapper<Question>().map(parsedObject)
    return result!
}
```

Instead of writing this method for each model in my app (for instance, replacing Question with Answers) I would want to create a Generic method for it. I have been trying it without success.

```swift
static func parse<T: Mappable>(data: NSData, toClass: T.Type) -> T {
    var parseError: NSError?
    let parsedObject: AnyObject? = NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions.AllowFragments, error:&parseError)
    let result = Mapper<T>().map(parsedObject)
    return result!
}
```

I would appreciate any help you might provide me.

thanks,

**Comment by tristanhimmelman** [comment]
It looks to me like your code should work. Can you be more specific about the issue you are having?

One note:
You should be able to remove the `toClass: T.Type` section of the function definition. If you remove it, you will just have to define the type of the variable which this function assigns to so that the compiler can infer the type T. For example your code would look something like:
```
let answer: Answer = parse(data: someData)
```
instead of: 
```
let answer = parse(data: someData, toClass: Answer.self)
```

If you are planning to use this code to parse HTTP calls into models, you might be interested in checking out https://github.com/tristanhimmelman/AlamofireObjectMapper. It is an extension to Alamofire which uses ObjectMapper to automatically convert your responses to objects. Hope this helps

**Comment by MoralAlberto** [comment]
Thanks!
