### ISSUE TITLE
Class cluster support

### ISSUE THREAD

**Issue by hankbao** [Hearst-DD/ObjectMapper#211]
We're currently using Mantle to map JSON to object. And class cluster support is very handy with Mantle. So I'd like to know if ObjectMapper has any plan to support class cluster?

**Comment by andrebraga** [comment]
https://github.com/Hearst-DD/ObjectMapper/issues/195, check my last comment there. Class clusters are possible, only not with ```init?``` as the initialiser.

**Comment by tristanhimmelman** [comment]
I've just created an experimental branch with support for Class clusters:
https://github.com/Hearst-DD/ObjectMapper/tree/class-clusters

I created a `Mappable` sub protocol called `MappableCluster`:
```
public protocol MappableCluster: Mappable {
	func newInstance(map: Map) -> Mappable?
}
```

There is an example in the ClassClusterTests.swift file. Here it is:
```swift

class Vehicle: MappableCluster {
	var type: String?
	
	required init?(_ map: Map){}
	
	func newInstance(map: Map) -> Mappable? {
		if let type = map["type"].currentValue as? String {
			if type == "car" {
				return Car(map)
			} else {
				return Bus(map)
			}
		}
		return nil
	}
	
	func mapping(map: Map) {
		type <- map["type"]
	}
}

class Car: Vehicle {
	var name: String?
	
	required init?(_ map: Map){
		super.init(map)
	}
	
	override func mapping(map: Map) {
		super.mapping(map)
		
		name <- map["name"]
	}
}

class Bus: Vehicle {
	required init?(_ map: Map){
		super.init(map)
	}
	
	override func mapping(map: Map) {
		super.mapping(map)
	}
}
```
Usage: 
```swift
let JSON = [["name": "Honda", "type": "car"], ["type": "bus"]]	
if let vehicles = Mapper<Vehicle>().mapArray(JSON){
	print(vehicles)
}
```
@andrebraga @hankbao feedback is welcome

**Comment by andrebraga** [comment]
Should work, only not for Core Data, not for keyed cache systems, and not for anything that actually commits something to persistent storage (disk, network, whatever) and is retrieved back by a (combination of) unique key(s)... I simply cannot understand how Realm people aren't giving a damn about duplication, unless Realm itself deals with it transparently. I admit I was enticed by Realm but didn't really delve into it because back then it lacked something approaching the convenience of NSFetchedResultsController.

I understand the conceptual beauty of using ```init?```, but it's simply impossible to achieve with it the same power that a static/class method brings. To wit: the way I structured my code, I have only one implementation of ```newInstance```, it applies to the base class only, it deals with both class clusters and uniquing, and individual models are as terse as they should be. Unfortunately having both ```init```and ```newInstance``` is just confusing. There is way more power and simplicity to be achieved from using ```newInstance``` exclusively, especially because ```init```ialiser requirements are **way** more convoluted than a simple static/class method. To note: there are severe restrictions to implementing ```init``` on an extension.

But let's get to the bare basics here. Effectively, class clusters and unique model retrieval depend on the same mechanism: returning on initialisation something other than a freshly created instance.

I would simply love if the language allowed returning a different ```init``` than the one that's allocated, like Objective-C did, but it is evident that Swift won't offer this capability by any means other than a class method. The moment they chose to collapse allocation and initialisation to be one and the same, we either bridge to Objective-C, or we use a static/class method as the instance provider.

**Comment by damienrambout** [comment]
About this `func newInstance(map: Map) -> Mappable?` function signature. Isn't it dangerous to simply return a `Mappable`? It does not ensure it will be the same type of the called class (e.g. a subclass of `Vehicle`). Any kind of object that conforms to `Mappable` and is not a `Vehicle` could be returned. In such a situation, mapping a `[Vehicle]` variable would probably produce a runtime exception since an non-vehicle object is being inserted into a `[Vehicle]` type.
It does not seem safe from a Swift point of view.

**Comment by tristanhimmelman** [comment]
@damienrambout, I agree it is not that safe, but as you said I cannot think of another solution at the moment.

@andrebraga why wouldn't this approach work for keyed cache system? It seems to me that the newInstance function could returned the cached/persisted object.

**Comment by andrebraga** [comment]
@tristanhimmelman specifically in the Core Data case the fact that the proposed ```newInstance``` is an instance method forces you to create a dummy instance and discard it. This is somewhat troublesome because creating an ```init?(_ map: Map)``` that takes no arguments other than map forces many boring details: the use of a definite managed object context (currently I create child contexts on the fly to sync a batch of objects, possibly discarding the whole context if/when an error occurs); managing managed object context threading; dealing with the fact that if said m.o.c. ends up being a main thread one there is a possibility of database corruption if you're using UIManagedDocument with automatic saves.

Not to mention the fact that there are strict requirements on the semantics of Swift ```init```ialisers that prevents one from implementing them on an extension, which screws up retroactive modelling.

All in all the old protocol worked perfectly fine :stuck_out_tongue:

**Comment by andrebraga** [comment]
@damienrambout I'm using generics and type inference to ensure the proper class (or struct) is instantiated depending on the web service called. There are more ways to ensure safety, having a protocol be the return type of a method isn't any less safe when you structure your code as a whole to prevent such errors :smiley:

**Comment by tristanhimmelman** [comment]
@andrebraga I agree that creating the dummy instance is not a great approach. However, I don't think there is an approach to checking is a generic type `T` is a subtype which creating the dummy variable. Any suggestions on that implementation would be appreciated

**Comment by tristanhimmelman** [comment]
@andrebraga I didn't realize I had made the newInstance function an instance function. That was definitely an accident. I am updating the code.

**Comment by andrebraga** [comment]
If you check my implementation of ```newInstance``` there's a test if the class type itself conforms to the protocol, by checking the protocol type. It should be possible to test the generic type the same way.

https://github.com/Hearst-DD/ObjectMapper/issues/195#issuecomment-140896718

It should be then possible to not run ```N(map)``` on a dummy instance like you did here:

https://github.com/Hearst-DD/ObjectMapper/commit/5b803582bb31acb4f875f21eb1c9c90cf4b57412#diff-a9498ca83904e6eb2c05ea55fe3c5a1dR181

by checking for the protocol conformance at the type level first. :smiley:

**Comment by andrebraga** [comment]
Just verified it here, it's definitely possible to test the generic type like that. :smiley:

**Comment by tristanhimmelman** [comment]
@andrebraga thanks for the pointer. I've pushed my changes using your suggestion

**Comment by laxmisa** [comment]
@tristanhimmelman Do you know if this would be merged into master anytime soon?

**Comment by tristanhimmelman** [comment]
@laxmisa, I am still evaluating whether I should update the protocol or merge this into master. Sorry for the delay. I will make sure to keep this branch up to date in the meantime

**Comment by mabril** [comment]
With this branch I managed to deserialize an array of class cluser. 
But... how to deserialize? This is my code

    let transform = TransformOf<[FilterBase], [[String:AnyObject]]>(fromJSON: { (value:  [[String:AnyObject]]?) -> [FilterBase]? in
            // transform value from String? to Int?
            return  Mapper<FilterBase>().mapArray(value)
            }, toJSON: { (value: [FilterBase]?) ->  [[String:AnyObject]]? in
                // transform value from Int? to String?
                if let value = value {
                    return Mapper().toJSONArray(value)
                }
                return nil
        })
        
        filters <- (map["Filters"],transform)

**Comment by tristanhimmelman** [comment]
@mabril it seems to me that you don't need to use this custom transform at all...

Does the following not work?
```
filters <- map["Filters"]
```

**Comment by mabril** [comment]
Exactly. I relalized of it minutes after posting. Now I only use the custom transform for deserialize. When I need to serialize I just use:
filters <- map["Filters"]

Thanks!

**Comment by tristanhimmelman** [comment]
Closing as class cluster support has been added to master.
