### ISSUE TITLE
Simplify the mapping operation

### ISSUE THREAD

**Issue by lexrus** [Hearst-DD/ObjectMapper#219]
This lib is great and very handy to use especially combined with AlamofireObjectMapper. But in one of my project I had to type a lot of `map["xxx"]` due to a very complex JSON. Further more, I have to type every property name at least 3 times in a single Model declaration. Then I saw [Himotoki](https://github.com/ikesyo/Himotoki), its `<|` is much more simplified and easy to type. And no need to type `aLongPropertyName = map["aLongPropertyName"]`.

``` swift
static func decode(e: Extractor) -> Group? {
        // Pass the initializer function and the arguments for
        // that function to `build()`.
        return build(Group.init)(
            e <| "name",
            e <| "floor",
            e <| [ "location", "name" ], // Parse nested objects
            e <||? "optional" // Parse optional arrays of values
        )
    }
```

I'd appreciate it if you could add such operators.

**Comment by bassebaba** [comment]
I would like an option to take this one step even further.
For this json:
`{
    "name": "bassebaba",
    "age": 31337,
    "isAwesome": true
}`

If I have:
`class person : Mappable
{
var name: String?
var age: Int?
}`

I would like to automagically map this without the `mutating func mapping(map: Map)` function.
Just like "ah okay, I have 'name' in the json and I have a string in the class named "name", lets automap that. Same thing for age. The bool is missing in the class, no problem lets just skip that one"

Because now, it's a total redundancy if I name my classes exactly as the json.

**Comment by tristanhimmelman** [comment]
ObjectMapper is a strongly typed compile time mapping library. This means that it cannot dynamically read variable name strings to use for mapping. I have considered adding this type of functionality, however, (for the moment) I have decided against it as the reflection APIs are quite slow which would result in worse mapping performance. I believe that maintaining fast mapping is preferable to reducing the amount of boilerplate code (which is pretty minimal in my opinion).

**Comment by lexrus** [comment]
@tristanhimmelman Is there any benchmark of reflection APIs?
@bassebaba I just found another lib which use reflection to map keys automatically. https://github.com/johnlui/JSONNeverDie

**Comment by tristanhimmelman** [comment]
@lexrus I don't actually have any benchmarks... this is information that I have heard anecdotally from others and blogs. It's possible that it is incorrect...

With that said, I think it may be difficult to integrate reflection into this library due to it's static nature. If you have time to experiment, however, that would be great! Any help/feedback is much appreciated.
