### ISSUE TITLE
Mapper().toJSONString calls the setter for every mapped property

### ISSUE THREAD

**Issue by arothberg** [Hearst-DD/ObjectMapper#255]
When calling Mapper().toJSONString for a Mappable object, I see that the setter is called for every property mapped in the mapping() function.

``` swift
class foo() : NSObject, Mappable
{
       var title: String? { didSet { doSomething("Title") } }
       
       func mapping(map: Map) {
           title <- map["Title"]
       }
}
```
when `let json = Mapper().toJSONString(fooInstance, prettyPrint: true)` executes you can see that `doSomething` is called for Title.  It's happening when the property is mapped in the `mapping` function.  It seemed counterintuitive to me that it would set anything when it's strictly an output operation.

Is there a way to generate a JSON string w/o it setting every mapped property on the input object?

Thanks!

**Comment by tristanhimmelman** [comment]
ObjectMapper is not actually setting each property during JSON generation. This issue is happening due to the fact that ObjectMapper handles object creation and JSON creation via the same mapping operator `<-`. This mapping operator is defined with an `inout` flag which signals to the system that the passed in object may be modified. This is likely what is triggering the `didSet` call.

So unfortunately, there is no mechanism available for writing JSON which will not trigger the didSet closure.
