### ISSUE TITLE
JSonify of Nested Array of nested Array or Array not working

### ISSUE THREAD

**Issue by mathieudebrito** [Hearst-DD/ObjectMapper#297]
Hi Guys !

I trying to jsonify this field :

    var coordinates:Array<Array<Array<Double>>>!

The mapping from Json works pretty well

    func mapping(map: Map) {
        type            <- map["type"]
        coordinates     <- map["coordinates"]
    }

But the reverse (from object to json) does not stringify the value of coordinates.
The result I get from the 'normal way' (`Mapper().toJSONString(multiLineString, prettyPrint: true)`)
gives me the following result :

 `{"type":"MultiLineString", "coordinates"}`

What can I do ?

Thanks

**Comment by tonyli508** [comment]
Why would you do, `var coordinates:Array<Array<Array<Double>>>!` instead of `var coordinates:Array<Double>!`.

then in the 
```swift
func mapping(map: Map)  {
      coordinates     <- map["coordinates.0.0"]
}
```

I know it's not support toJSON array mapping yet, I have a open PR for this: https://github.com/Hearst-DD/ObjectMapper/pull/259, I don't know if they will merge that. 

But you can always try my fork here: https://github.com/tonyli508/ObjectMapperDeep

cocoapods: pod 'ObjectMapperDeep', '= 0.20.0'

**Comment by mathieudebrito** [comment]
Well, my bad, I should have shown the possible values of coordinates :p

my coordinates looks like this : `"[[[1,1], [2,2], [3,3]], [[1',1], [2',2'], [3',3']]]"`
And I need to get all of these data. This is why `Array<Array<Array<Double>>>`

I will definitely take a look at your fork !
Thx :)

**Comment by tonyli508** [comment]
I updated my PR https://github.com/Hearst-DD/ObjectMapper/pull/259, should be fixed, you can use following cocoapod:

pod 'ObjectMapperDeep', '= 0.20.2'

**Comment by IlyaRakov** [comment]
+1
