### ISSUE TITLE
NSManagedObject

### ISSUE THREAD

**Issue by sgermain06** [Hearst-DD/ObjectMapper#330]
Any way this could be used to map NSManagedObject subclasses?

Right now, trying to overload the init method won't let me initialize an NSManagedObject.

**Comment by levieggert** [comment]
Hey sgermain06, I just went through the same thing.  

Mapper.swift has some methods for mapping to an existing object.  You would have to use those.

I created a class to handle this for me if you'd like to check it out.  Maybe the author can implement something similar.

[EntityMapper.txt](https://github.com/Hearst-DD/ObjectMapper/files/62670/EntityMapper.txt)
[Entity.txt](https://github.com/Hearst-DD/ObjectMapper/files/62669/Entity.txt)

You can use EntityMapper.swift to map NSManagedObjects by providing the entity name and context.  I added a MappableEntity protocol that inherits from Mappable.  So your NSManagedObjects would use the MappableEntity protocol.  Because MappableEntity is Mappable, you'd still be able to take advantage of using other Mappable methods like converting your NSManagedObject to JSON.

**Comment by tristanhimmelman** [comment]
@levieggert thanks. 

@sgermain06 you can search the Github issues as others have discussed this in the past. I personally have not used ObjectMapper with CoreData so I cannot help.

**Comment by gezman** [comment]
@tristanhimmelman 
Could you please advice what you use with CoreData?

**Comment by tristanhimmelman** [comment]
@gezman... I don't use CoreData much in general.

However, I'm pretty sure you can use ObjectMapper along side CoreData

Take a look at the `objectForMapping` function. This will allow you to create / or retrieve an existing object to use during mapping. 

Also looking into the MapContext. You could use that to store you CoreData coordinator and have it passed around within the `Map` object during mapping. 

Hope this helps
