### ISSUE TITLE
Non numeric value from json is failing for numeric model's property 

### ISSUE THREAD

**Issue by NiteshKumar-webonise** [Hearst-DD/ObjectMapper#377]
https://github.com/Hearst-DD/ObjectMapper/issues/352#issuecomment-168196617
Thanks for reply :)
I will take care of it.
but still if i get nil user how to check where is the problem, which property type we need to change as per json response ?

As for single nil property, we cannot nullify the whole object. Except one property other should at least be populated. That exceptional property should get its default value in this case.

**Comment by tristanhimmelman** [comment]
Usually if you get a nil object returned from ObjectMapper it is because there is a problem with your JSON input. Either it is not valid JSON or it cannot be parsed and cast into type `[String : AnyObject]`.

> Non numeric value from json is failing for numeric model's property

This is expected behaviour. ObjectMapper expects the JSON to be of the appropriate type to be parsed, otherwise it returns nil. You can always use a Transform (see README) if you need to map a non numeric value to a numeric model. For example `"grade" : "100"` contains a String value where you may really want an `int`. A transform can convert this during mapping.
