### ISSUE TITLE
ObjectMapper-tvOS framework crashes the compiler with segmentation fault 11

### ISSUE THREAD

**Issue by MugunthKumar** [Hearst-DD/ObjectMapper#387]
1. Create a blank tvOS app.
2. Add ObjectMapper to Cartfile and drag the framework to your project.
3. Add a new file implementing `Mappable`

```
import UIKit
import ObjectMapper

class Channel: Mappable {
  var identifier : String!

  func mapping(map: Map) {
    identifier <- map["id"]
  }
}
```

Try building the project. You will see that the compiler crashes. I'm using ObjectMapper in an iOS app without problems. Not sure what is causing this on tvOS.

I made a demo project illustrating this.
https://dl.dropboxusercontent.com/u/2441850/Test.zip

**Comment by tristanhimmelman** [comment]
The above example doesn't correctly implement `Mappable`. You are missing the `init?` function.

Otherwise, I'm not sure what is causing the seg fault...

I did just pushed an update which enables bitcode for tvOS and watchOS. Please make sure you are using that as having bitcode enabled is a requirement for tvOS.

Hope this helps

**Comment by MugunthKumar** [comment]
You are right. Adding the `init?` function fixes the crash. Swift compiler still doesn't point out to the right error.

The tvOS/watchOS stuff is compiler specific I guess. I'm closing this issue
