### ISSUE TITLE
Potential error in Mapper.swift

### ISSUE THREAD

**Issue by PhilCai1993** [Hearst-DD/ObjectMapper#400]
```
public func map(JSON: AnyObject?) -> N? {
		if let JSON = JSON as? [String : AnyObject] {
			return map(JSON)
		}

		return nil
	}
```
In this function, if JSON is not Dictionary, it returns nil.
But Is it possible JSON is a String or sth else?
```
public func map(JSON: AnyObject?) -> N? {
		if let JSON = JSON as? [String : AnyObject] {
			return map(JSON)
		}  else if let JSON = JSON as? xxx {
                  return yyy  
              }

		return nil
	}
```

**Comment by tristanhimmelman** [comment]
I agree that this function is a bit odd and can lead to confusion at times. I think the better solution would be to actually remove the function completely and only have two versions of the map function, one that takes `String` and one that takes `[String : AnyObject]`. I am still debating whether I will do this because I don't want to break the API for people without good reason. Thanks for the heads up though
