### ISSUE TITLE
DateTransform not Converting milliseconds to Date accurately

### ISSUE THREAD

**Issue by umairalighumman** [Hearst-DD/ObjectMapper#402]
I am using objectmapper to parse json to model. when i parse millisecond to date it could not accurately calculate date. I resolve this issue by dividing 1000 to millisecond in Date Transform  .

**Comment by tristanhimmelman** [comment]
`DateTransform` currently requires an input of seconds not milliseconds. 

If you want to add functionality to DateTransform so that it can optionally support milliseconds, I would be happy to accept a Pull Request. You could add an optional parameter to the initializer that configures the transform to operate on milliseconds.
