### ISSUE TITLE
How to write a failable init from JSON

### ISSUE THREAD

**Issue by SimplGy** [Hearst-DD/ObjectMapper#450]
Sorry I keep nosing in here. The problem space is just really interesting to me right now, I'm working on something tangental.

Call it a learning exercise, or a preference for constructors over factories--I'm trying to write the initialization of a model object as a failable init that accepts json, like this:

```swift
extension Mappable {
  init?(json: [String : AnyObject]) {
    self.init( Map(mappingType: .FromJSON, JSONDictionary: json) )
  }
}
```

I only get empty objects back. I'm not sure why, but that's not a big surprise, since I don't understand the protocol's requirement for an empty `init?(map: Map)` in the first place. Maybe the init is just a compiler-placating placeholder, since the object is mutated.

If that's the case, maybe I need to mutate after init. This works for my test application:

```swift
extension Mappable {
  init?(json: [String : AnyObject]) {
    let map = Map(mappingType: .FromJSON, JSONDictionary: json, toObject: true)
    self.init(map)
    self.mapping(map)
  }
}
```

Question for the maintainer--is this a correct way to implement `Mappable#init?(json: [String:AnyObject])`?

The process of initialization for Mappables is (moving towards "was") a big point of confusion for me. Is it worth adding some discussion in the docs? Want me to draft it?

**Comment by tristanhimmelman** [comment]
Hi @SimplGy, `the init?` requirement is in place so that ObjectMapper can create objects of your given model during mapping. It does not by default allow you to create a model simply by passing in a `Map` object.

However, I believe the functionality you are trying to add already exists. See 
https://github.com/Hearst-DD/ObjectMapper/blob/master/ObjectMapper/Core/Mappable.swift#L32

I have not added this to the documentation yet... and unfortunately Xcode autocompletion does not display these functions.

**Comment by SimplGy** [comment]
Look at that, `init?(JSON)` sure does already exist and it's a beautiful implementation. I'll use that, thanks.

I'm still unclear on why my implementation worked, (and what was wrong with it, because I'm sure something was). That has to do I think with the difference between Map and Mapper and will be my own private journey. Thanks Tristan!
