### ISSUE TITLE
map toObject destroys references to nested Objects

### ISSUE THREAD

**Issue by kingarthur23** [Hearst-DD/ObjectMapper#496]
Hey, I found a Problem. If I pass a dcitionary oder string to an object, it destroys the references.

Example: 

`public class AType: Mappable {
    var title: String?
    
    required public init?(_ map: Map) {
    }
    
    public func mapping(map: Map) {
        title   <- map["title"]
    }
}

`public class BType: Mappable {
    var id: String?
    var classA: AType?
    
    required public init?(_ map: Map) {
    }
    
    public func mapping(map: Map) {        
        id              <- map["id"]
        classA      <- map["classA"]
    }
}
`
let bTypeObject = BType()

In the background all vars of the bTypeObject got filled.
References before passing the Dictionary to the bTypeObject:
I print it in the console

po bTypeObject 
`<Project.BType: 0x7f8c485535d0>`

po bTypeObject.classA
`<Project.AType: 0x7f8c48705030>`

Now I pass the Dictionary to the Object and show u the new references
`
Mapper<BType>().map(modelJson, toObject: model)
`

po bTypeObject 
`<Project.BType: 0x7f8c485535d0>`

po bTypeObject.classA
`<Project.AType: 0x7fa9d0c6fe60>`

You can see, that the reference to the BType object is still the same, but the reference to bTypeObject.classA is an other. It seems, the  framework creates an new AType object and pass it to bTypeObject.classA.

Do you have an Idea how I can fix that?

EDIT:

> Ah, I have seen, that this problem exists only with arrays. 

If the var classA is an Array, all objects in it, loosing their reference

`  public class BType: Mappable {
          var id: String?
          var classA: [AType]?
   }
`

**Comment by tristanhimmelman** [comment]
That's correct. This happens because ObjectMapper cannot know with any certainty that an object in an array should map to a certain object in a JSON dictionary. I considered using the array index as a mechanism to implment `toObject` mappings however I don't think that is not a very robust solution as arrays may have their orders changed.

One solution to your situation is to use the `objectForMapping(map: Map) -> Mappable` function. This function is executed prior to mapping each object. It allows you to return an existing object reference to use during mapping. Hope this helps
