### ISSUE TITLE
map(JSON: AnyObject?) supposed to take dictionary or string, but ignores string input.

### ISSUE THREAD

**Issue by nikita-leonov** [Hearst-DD/ObjectMapper#504]
Based on my way of thought and existing comments for map(JSON: AnyObject?) it should take string or dictionary. Currently string inputs are ignored:

```
/// Maps a JSON object to a Mappable object if it is a JSON dictionary or NSString, or returns nil.
	public func map(JSON: AnyObject?) -> N? {
		if let JSON = JSON as? [String : AnyObject] {
			return map(JSON)
		}

		return nil
	}
```

Is there a reason why it was developed like this and it even mismatching documentation or should I provide PR to fix it?

**Comment by svetlyo** [comment]
The comment is outdated - take a look at the code when it was introduced -https://github.com/Hearst-DD/ObjectMapper/commit/741908cfc48225d646425faf5b9d58a03c84bfc1. Since then the handling of String was extracted in another overloaded version of map:

https://github.com/Hearst-DD/ObjectMapper/blob/master/ObjectMapper/Core/Mapper.swift#L85

```swift
	/// Map a JSON NSString to an object that conforms to Mappable
	public func map(JSONString: NSString) -> N? {
		return map(JSONString as String)
	}
```

**Comment by nikita-leonov** [comment]
I see. But what if JSON: AnyObject is actually String, but not [String: AnyObject] in current implementation? It will return nil. Is there Mapper level function that take both [String: AnyObject] or String and return Object?

**Comment by svetlyo** [comment]
If you have a `String` disguised as `AnyObject` (a variable of type `AnyObject` which was assigned a `String` value) the overloading won't work and `public func map(JSON: AnyObject?) -> N?` would be called and you'll get `nil` - you're right about that.  As far as I see it there is no such function - it would be a giant `switch` with `as?` cases that tries different types. Currently the whole switching based on the type of the thing that you pass to `map` is done via function overloading which does not see the real, dynamic type - otherwise it would be polymorphic. Sadly swift does not support multiple dispatch (https://en.wikipedia.org/wiki/Multiple_dispatch)

**Comment by nikita-leonov** [comment]
Yes, I do have String discussed as Object. Maya currently have such method in place:
```
func mapJSON() throws -> AnyObject {
        do {
            return try NSJSONSerialization.JSONObjectWithData(data, options: .AllowFragments)
        } catch {
            throw Error.Underlying(error)
        }
    }
```
NSJSONSerialization.JSONObjectWithData may return both String & Dictionary. It unfortunately does not work well with mapping in ObjectMapper. Anyway there is much deeper problem in ObjectMapper, which is Mappable can be reconstructed only from JSON Objects, but not from other valid JSON objects. I will likely need to find other tooling to deal with situation that I have. Thanks.
