### ISSUE TITLE
Upgrade to version 1.5

### ISSUE THREAD

**Issue by vunhatminh241191** [Hearst-DD/ObjectMapper#572]
Hi,

I have a trouble problem when I update to Xcode 8 - Swift 3.0, my Xcode could not read Object Mapper anymore. I read in the release version, you guys also support Swift 2.3. Could you guys tell me how can I update to the newest version of Object Mapper, a version 1.5, because my version that I am using right now is 1.3.

I am very appreciate any helps. Thanks

**Comment by minhnguyen1990** [comment]
I have the same problem. Can you convert the current code to Swift 3 syntax? Please!

**Comment by juliengdt** [comment]
The syntax conversion is done, but tag/version has not been pushed to cocoapod, we are waiting some action from @tristanhimmelman

**Comment by cherishloveyou** [comment]
version 1.5 miss

**Comment by tristanhimmelman** [comment]
@juliengdt I tried to push the cocoapod last night but the push utility was having trouble building the project. I haven't able to sort out the issue yet. Hopefully I can figure out a fix soon

**Comment by tristanhimmelman** [comment]
I just released v 2.0.0 on Cocoapods

**Comment by kristijanexads** [comment]
Sorry to comment on closed issue, can you tell me if its all sorted for Carthage? Tnx a lot

**Comment by tristanhimmelman** [comment]
@kristijanexads v2.0.0 is update and running for Carthage

**Comment by kristijanexads** [comment]
@tristanhimmelman I had a problem with Carthage v2.0.0 because it's meant to work with Swift3 and I can't update to Swift3 at the moment (because some other frameworks that I'm using aren't updated) so I ended up with this 
<code>github "Hearst-DD/ObjectMapper" ~> 1.5</code>  
and run this command 
<code>carthage update --platform iOS --toolchain com.apple.dt.toolchain.Swift_2_3 ObjectMapper</code>
