### ISSUE TITLE
ImmutableMappable as a property in Mappable

### ISSUE THREAD

**Issue by ivanbruel** [Hearst-DD/ObjectMapper#668]
I've been trying to have a clear example where Mappable and ImmutableMappable co-exist in a project to make sure my extensions for `Moya` work properly.

I have a [Repository](https://github.com/ivanbruel/Moya-ObjectMapper/blob/master/Sample/Demo/Repository.swift) which implements `Mappable` and an [Owner](https://github.com/ivanbruel/Moya-ObjectMapper/blob/master/Sample/Demo/Owner.swift) which implements `ImmutableMappable`.

As far as I can tell these two should be able to co-exist in the same serialization hierarchy.

I seem to be hitting a wall when it comes to the type checking in the `Mapper` class.

```
assertion failed: 'ImmutableMappable' type requires throwing version of function map(JSON:)  - use 'try' before map(JSON:): file /Users/ivanbruel/Documents/Moya-ObjectMapper/Sample/Pods/ObjectMapper/Sources/Mapper.swift, line 108
```

What's the reasoning behind not letting `map(JSON:)` work with `ImmutableMappable` properties?

For sake of issue completion, by changing the function into the code below I can make it work.

```swift
/// Maps a JSON dictionary to an object that conforms to Mappable
public func map(JSON: [String: Any]) -> N? {
	let map = Map(mappingType: .fromJSON, JSON: JSON, context: context)
		
	if let klass = N.self as? StaticMappable.Type { // Check if object is StaticMappable
		if var object = klass.objectForMapping(map: map) as? N {
			object.mapping(map: map)
			return object
		}
	} else if let klass = N.self as? Mappable.Type { // Check if object is Mappable
		if var object = klass.init(map: map) as? N {
			object.mapping(map: map)
			return object
		}
	} else if let klass = N.self as? ImmutableMappable.Type { // Check if object is Mappable
		if let object = try? klass.init(map: map) as? N {
			return object
		}
	} else {
		// Ensure BaseMappable is not implemented directly
		assert(false, "BaseMappable should not be implemented directly. Please implement Mappable, StaticMappable or ImmutableMappable")
	}
	
	return nil
}
```

**Comment by devxoul** [comment]
@ivanbruel, Here are the reasons:

1. I also had similar consideration when I was developing the ImmutableMappable. I concluded with myself, that users would not use `ImmutableMappable` with `Mappable`. (Why would they even do that?)

    We can discuss about this if you have different idea.

2. According to @tristanhimmelman from #617:

    > I think that if you define an model as `ImmutableMappable` you expect a error to be thrown if something was not correctly map.

    `map()` function on `BaseMappable` cannot throw an error if `ImmutableMappable` is not correctly mapped.

**Comment by ivanbruel** [comment]
Wouldn't it be better to distinguish between a top-level call and an inner call?
Where the top-level call would enforce the `try` for the `ImmutableMappable` class/struct.
This would eliminate any kind of library limitation, where if you use `ImmutableMappable` you cannot use a `Mappable` class in the hierarchy.
This is especially noticeable when migrating a project into the more compiler friendly `ImmutableMappable` where there are no ImplicitlyUnwrappedOptionals.

**Comment by tapi** [comment]
@devxoul To answer your question
> Why would they even do that?

Im currently trying to incorporate ObjectMapper into an older code base. The entry point from our old parsing into the new is necessarily nullable and so mappable made sense to me. However within the new work I had hoped to use structs and immutable properties for the relationships.

There was nothing in the documentation of `ImmutableMappable` that suggested they shouldn't be used interchangeably. 
In fact changing `property <- map["property_value"]` to `property = (try? map.value("property_value")) ?? "" works just fine. 

I think documentation about this would be a good start. I was caught off guard by the fact that this is a runtime issue rather than a compile time one. I think I see why, but I wonder if there isn't someway of resurfacing  the fact that `<-` should throw for `ImmutableMappable`.

A quick test shows that an `ImmutableMappable` specific override that throws is caught up correctly but thats a lot of operator overloads 😬

**Comment by devxoul** [comment]
@ivanbruel @tapi #780 is a patch for this issue. This PR makes it available to make an `ImmutableMappable` as a property of `Mappable`.

**Comment by tristanhimmelman** [comment]
I just merged @devxoul PR which should address the issue here.
