### ISSUE TITLE
Is ObjectMapper still maintained? 

### ISSUE THREAD

**Issue by pietrorea** [Hearst-DD/ObjectMapper#970]
What's the status of this repo? Lots of open issues and pull requests plus no releases in 6 months make me think that ObjectMapper has been abandoned. Swift 4.1 also broke parsing of Floats, which has been a critical bug many of us have had to fix.

Would love to hear from @tristanhimmelman about any future plans, which would in turn help us with our roadmaps.

See these issues for the Float parsing problem in Swift 4.1: 
- https://github.com/Hearst-DD/ObjectMapper/issues/954
- https://github.com/Hearst-DD/ObjectMapper/issues/955
- https://github.com/Hearst-DD/ObjectMapper/pull/959

**Comment by tristanhimmelman** [comment]
Hi everyone, I have gone ahead and merged the Swift 4.1 float fix. 

To be perfectly honest I have not had much time to spend maintaining this project this year. I will try carve out more time to make sure that any important PRs are handled. I have been maintaining this project alone since it was created in very early Swift days so needless to say it has consumed a lot of my time. With that said, I really appreciate any help with code fixes and issue handling as I cannot do it all myself.

Please see v3.2.0 for the latest
